spring:
  threads:
    virtual:
      # 启用虚拟线程
      enabled: true
  profiles:
    active: local
  config:
    import:
      - file:config/${spring.profiles.active}/flyway.yml
      - file:config/${spring.profiles.active}/knife4j.yml
      - file:config/${spring.profiles.active}/oss.yml
      - file:config/${spring.profiles.active}/mybatis-flex.yml
      - file:config/${spring.profiles.active}/mysql.yml
      - file:config/${spring.profiles.active}/page-helper.yml
      - file:config/${spring.profiles.active}/redis.yml
      - file:config/${spring.profiles.active}/sa-token.yml
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  application:
    name: admin-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
app:
  version: @project.version@
  upload-dir: D://Business/school-project/uploads/
sz:
  # 是否启用数据权限拼接
  data-scope:
    enabled: true
    # 数据逻辑实现最小验证（查询）单位：dept 部门（dept_scope字段）、user 用户 (create_id 字段),默认user。
    logic-min-unit: user
  debounce:
    # 是否启用防抖功能
    enabled: true
    # 全局防抖时间，单位毫秒（默认1000ms）
    global-lock-time: 500
    # 是否忽略GET请求
    ignore-get-method: true
  # 生成工具
  generator:
    path:
      # 前端项目地址
      web:
      # 后端项目地址，默认自动检测springboot项目路径，无需配置。
      api: E://code//Gitlab//sz-framework//sz-admin
    # 模块名，指定代码生成的模块
    module-name: sz-service
    service-name: sz-service-admin
    global:
      author: sz-admin
      packages: com.sz.admin
      ignore-table-prefix:
        enabled: true
        prefixes:
          - t_
  # 微信生态
  wechat:
    # 小程序
    mini:
      app-id: wxe89097f03e90abe1 #wxf912cb0400975d41 #wxda066d2e8ee97c2e #wxe89097f03e90abe1
      app-secret:  43658aa83ff02eeeebfbb6806c2c5594 #822e26bcdcb16f0ef7a3f067341ab69b #7977e8184146fcb4d07ea2770d2fbe8f
      templates:
        CHECK_RESULT: BDPxr-H7GoR74_HNaIyGUqGpdLHQzQib0npe6a9M4Jg #审核结果模板
        ALUMNI_APPLY: bwxZPB1Ukj4SWOXTGfktgvbNz4DTjxJ03J3OXHhmDZI #校友申请消息通知模板
#    pay:
#      mchId:
#      mchSerialNo:
#      privateKeyPath:
#      platformCertPath:
#      apiV3Key:
#      notifyUrl:
#      domain:
#      sandbox:
  cors:
    # 定义允许跨域请求的源（Origin）。可以设置为特定的域名、IP 地址或通配符。
    allowed-origins:
      - "*"
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "never"

# 本地文件上传配置
file:
  upload:
    base-path: D://Business/school-project/uploads/
    max-file-size: 10485760
    allow-overwrite: false